---
title: "Barplots Markdown"
author: "Janie Briglio"
date: "2/14/2018"
output: html_document
---
###Bar Graph Comparison of Border Patrol Apprehensions 
####2010
entering the data for 2010 and making a column and row for the total for the locations 
and the months
```{r}
data1 <- read.csv("2010 data.csv", header = TRUE, stringsAsFactors = FALSE)
rownames(data1) <- data1[,1]
data1 <- subset(data1, select= -c(Sector))
data1 <- rbind(data1, colSums(data1))
rownames(data1) <- c(rownames(data1)[-length(rownames(data1))], "Total")
data1 <- cbind(data1,rowSums(data1))
colnames(data1) <- c(colnames(data1)[-length(colnames(data1))], "Total")
```
bar graph of the totals for for each location 
```{r}
barplot(data1[1:9, 13], names.arg = rownames(data1)[1:9], 
        las=2,
        axisnames=TRUE,
        main="2010 Border Patrol Apprehensions by Sector",
        border="black",
        col="blue")
```


####2017
entering the data for 2017 and making a column and row for the total for the locations 
and the months
```{r}
data2 <- read.csv("2017 data.csv", header = TRUE, stringsAsFactors = FALSE)
rownames(data2) <- data2[,1]
data2 <- subset(data2, select= -c(Sector))
data2 <- rbind(data2, colSums(data2))
rownames(data2) <- c(rownames(data2)[-length(rownames(data2))], "Total")
data2 <- cbind(data2, rowSums(data2))
colnames(data2) <- c(colnames(data2)[-length(colnames(data2))], "Total")
```
bar graph for the totals of each location 
```{r}
barplot(data2[1:9, 13], names.arg = rownames(data2)[1:9], 
        las=2,
        axisnames=TRUE,
        main="2017 Border Patrol Apprehensions by Sector",
        border="black",
        col="blue")
```